### ISSUE TITLE
Small request: Adding an operator to search for an image lower than xxx pixel size.

### ISSUE THREAD

**Issue by mikhoul** [polywock/advanced-image-search#1]
Hi,

Could it be possible to and an operator to search for an image lower than xxx pixel size.Lot of time I want images in low resolution so being able to filter out let's say all images over 800*800 would be really useful for me

Regards :octocat: ​​​​​​

**Comment by polywock** [comment]
Hello, thanks for the star. I looked around but it doesn't look like they support that kind of filter.

**Comment by polywock** [comment]
I also looked into other search engines. It looks like Yandex supports it. To use, create a bookmark and set the URL to the following code.

```
javascript:location.replace(`https://yandex.com/images/search?text=${prompt("query? ")}&isize=lt&iw=${parseInt(prompt("width: "))}&ih=${parseInt(prompt("height: "))}`, "_blank")
```
