### ISSUE TITLE
Google SafeSearch blurring is turned on.

### ISSUE THREAD

**Issue by mitrooper** [polywock/advanced-image-search#4]
Hi,

Lately, when I try to search images with Advanced-Image-Search, Google Image Search SafeSearch blurring is always turned on and I'm not able to turn it off.
A standard Google Image Search does not have this problem, only with Advanced-Image-Search.

Hope you can help out.

Thank you.

**Comment by polywock** [comment]
Hi. Sorry, no longer possible to change safesearch settings through a URL parameter. Google now says `You don't have permission to change your SafeSearch setting. It's locked by safety settings applied to this browser.` Good news, it seems that you can just change it once in your settings and it will persist.

**Comment by polywock** [comment]
Fixed in the latest update (> 1.3). I also implemented a profiles feature in this update. If you end up using it, let me know if you encounter any issues with it.
