### ISSUE TITLE
When I press Enter button, two tabs open instead of just one!

### ISSUE THREAD

**Issue by DARTH-WAFER** [polywock/advanced-image-search#5]
When I hit the "Enter" button to search the image, two tabs open at the same time, instead of only one. it's a little weird because when I use the search button within the extension, everything works fine. is this issue with the extension or my browser?

**Comment by polywock** [comment]
Oops. Looks like I called the function twice. Fixed in the latest update. It should get approved within 24 hours.

**Comment by DARTH-WAFER** [comment]
wow. that was fast 🤝
thanks a lot. i use this extension on a daily basis for my work. you don't how much it means to me. 💜🤘

**Comment by polywock** [comment]
Glad to be of help! If you have any more questions/suggestions, just let me know. 👍
