### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by bobsage123** [polywock/advanced-image-search#6]
It doesn't look like this is working any longer. I've tried clearing my cookies, using a fresh browser with no extensions, etc but it no longer shows "10mp" etc on the google page after I do the search.

**Comment by polywock** [comment]
Hello. It's no longer showing up on the UI, but the results are all larger than 10MP. This might be a sign they're phasing out support for the larger than filter.

**Comment by bobsage123** [comment]
I think you're right, thanks for confirming.
